app/web_root/app.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# -----------------------------------------------

from flask import Flask, render_template, session, request, redirect, url_for
from .views.account import account
from .views.home import home
from .app_conf import AppConfig


def create_webapp():

    app = Flask(__name__)
    app.register_blueprint(account, url_prefix='/')
    app.register_blueprint(home)
    app.config.from_object(AppConfig)

    @app.before_request
    def check():
        if not session.get('user') and \
                not request.path.startswith('/static') \
                and request.path != '/login':
            return redirect(url_for('account.login'))

    @app.template_filter("split_path")
    def split_path(path):
        path_list = path.split('/')
        path_list = [
            [path_list[i - 1], '/'.join(path_list[:i])] for i in range(1, len(path_list)+1)]
        return path_list

    @app.errorhandler(404)
    def error(error_no):
        return render_template('error_404.html')

    return app

app/web_root/views/account.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# -----------------------------------------------

from flask import Blueprint, render_template, request, session, redirect, url_for, jsonify
from settings import settings

account = Blueprint('account', __name__)


@account.route("/")
@account.route('/login', methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template('account.html', app_name=settings.APPLICATION_NAME)
    else:
        username = request.form.get('user')
        password = request.form.get('pwd')
        if username == settings.LOGIN_USERNAME and \
            password == settings.LOGIN_PASSWORD :
            session['user'] = username
            return jsonify({"code": 200, "error": ""})
        else:
            return jsonify({"code": 401, "error": "用户名或密码错误"})


@account.route('/logout')
def logout():
    del session['user']
    return redirect(url_for('account.login'))

app/web_root/views/home.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# -----------------------------------------------

from settings import settings
from flask import Blueprint, render_template, current_app, send_from_directory, request, jsonify
from werkzeug.utils import secure_filename
import os
import time
import hashlib
import json
import glob,shutil

home = Blueprint('home', __name__)


def calc_md5(file):
    with open(file, 'rb') as f:
        h = hashlib.md5()
        chunk = f.read(8192)
        while chunk:
            h.update(chunk)
            chunk = f.read(8192)
        return h.hexdigest()


class DocumentReader:

    def __init__(self, real_path):
        self.real_path = real_path

    def analysis_dir(self):
        dirs = []
        files = []
        os.chdir(self.real_path)
        for name in sorted(os.listdir('.'), key=lambda x: x.lower()):
            _time = time.strftime("%Y-%m-%d %H:%M:%S",
                                  time.localtime(os.path.getctime(name)))
            if os.path.isdir(name):
                dirs.append([name, _time, '文件夹', '-'])
            elif os.path.isfile(name):
                file_type = os.path.splitext(name)[1]
                size = self.get_size(os.path.getsize(name))
                files.append([name, _time, file_type, size])
        return dirs, files

    @staticmethod
    def get_size(size):
        if size < 1024:
            return '%d  B' % size
        elif 1024 <= size < 1024 * 1024:
            return '%.2f KB' % (size / 1024)
        elif 1024 * 1024 <= size < 1024 * 1024 * 1024:
            return '%.2f MB' % (size / (1024 * 1024))
        else:
            return '%.2f GB' % (size / (1024 * 1024 * 1024))


@home.route('/index')
@home.route('/index/<path:path_uri>')
def index(path_uri=''):
    base_dir = settings.BASEDIR
    real_path = os.path.join(base_dir, path_uri).replace('\\', '/')

    if not os.path.exists(real_path):
        html = render_template('error_404.html')
    else:
        file_reader = DocumentReader(real_path)
        dirs, files = file_reader.analysis_dir()
        html = render_template('index.html',
                               app_name=settings.APPLICATION_NAME,
                               path=path_uri,
                               dirs=dirs,
                               files=files,
                               error_info=None
                               )
    return html


@home.route('/getMusicList', methods=["POST"])
def get_music_list():
    car_type = request.form.get('car_type')
    car_number = request.form.get('car_number')
    base_dir = settings.BASEDIR
    music_dir_list = [
        f'bgm/{car_type}/{car_number}',
        f'bgm/{car_type}/default',
        f'bgm/default'
    ]
    bgms = []
    rel_path = ''
    for i in music_dir_list:
        music_dir = os.path.join(base_dir, i)
        if not os.path.exists(music_dir):
            continue
        bgms = glob.glob(f'{music_dir}/*.mp3')
        if len(bgms) > 0:
            rel_path = i
            break
    fileinfo = []
    for i in bgms:
        if not os.path.isfile(i):
            continue
        filename = os.path.basename(i)
        fileinfo.append(
            {"name": filename, "url": f'/download/{rel_path}/{filename}', "md5": calc_md5(i)})
    return json.dumps(fileinfo)

@home.route('/getWarningSoundList', methods=["POST"])
def get_warning_sounds():
    base_dir = settings.BASEDIR
    sound_dir = os.path.join(base_dir,'warning-sound')
    sounds = glob.glob(f'{sound_dir}/*.wav')
    fileinfo = []
    for i in sounds:
        if not os.path.isfile(i):
            continue
        filename = os.path.basename(i)
        fileinfo.append(
            {"name": filename, "url": f'/download/warning-sound/{filename}', "md5": calc_md5(i)})
    return json.dumps(fileinfo)


@home.route('/download/<filename>')
@home.route('/download/<path:path>/<filename>')
def download(filename, path=None):
    if not path:
        real_path = settings.BASEDIR
    else:
        real_path = os.path.join(settings.BASEDIR, path)
    return send_from_directory(real_path, filename, mimetype='application/octet-stream')


@home.route('/upload', methods=['GET', 'POST'])
def upload():
    html = ''
    if request.method == 'POST':
        path = request.form.get('upload_path')
        file = request.files['upload_file']
        base_dir = settings.BASEDIR

        if file:
            filename = _get_filename(file)
            save_path = os.path.join(base_dir, path, filename)
            file.save(save_path)
            html = jsonify({"code": 200, "info": "文件：%s 上传成功" % filename})
        else:
            html = jsonify({"code": 201, "info": "未选择文件"})
    else:
        html = jsonify({"code": 201, "info": "禁止使用爬虫上传文件"})
    return html


def _get_filename(file):
    return file.filename
    # secure_filename 可以处理路径穿越等问题，但是会把文件名中中文去掉，故无法使用
    # return secure_filename(file.filename)


@home.errorhandler(500)
def error(error):
    return render_template('error_500.html')


@home.route('/createdir/<dirname>',methods=['POST'])
@home.route('/createdir/<path:path>/<dirname>',methods=['POST'])
def create_dir(dirname, path=None):
    if not path:
        real_path = settings.BASEDIR
    else:
        real_path = os.path.join(settings.BASEDIR, path)
    fullpath = os.path.join(real_path,dirname)
    if os.path.exists(fullpath):
        return jsonify({"code":304,"info":"目录已经存在"})
    try:
        os.makedirs(fullpath)
    except:
        return jsonify({"code":500,"info":"创建目录失败"})
    return jsonify({"code":200,"info":"创建目录成功"})


@home.route('/deleteResource/<dirname>',methods=['POST'])
@home.route('/deleteResource/<path:path>/<dirname>',methods=['POST'])
def delete_resource(dirname,path=None):
    if not path:
        real_path = settings.BASEDIR
    else:
        real_path = os.path.join(settings.BASEDIR, path)
    fullpath = os.path.join(real_path,dirname)
    print("fullpath : ",fullpath)
    if not os.path.exists(fullpath):
        return jsonify({"code":304,"info":"目录已经存在"})
    try:
        if os.path.isdir(fullpath):
            shutil.rmtree(fullpath)
        elif os.path.isfile(fullpath):
            os.remove(fullpath)
    except:
        return jsonify({"code":500,"info":f'删除目录{dirname}失败'})
    return jsonify({"code":200,"info":"删除目录成功"})

app/web_root/templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ app_name }}</title>
    <link rel="icon" href="{{ url_for('static',filename='img/favicon.png') }}">
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/signin.css') }}" rel="stylesheet">
    <script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
    <script>
        $(function () {
            $("#submit").click(function (event) {
                event.preventDefault();
                var userInput = $('input[name="user"]');
                var user = userInput.val();
                var pwdInput = $("input[name='pwd']");
                var pwd = pwdInput.val();
                $.post({
                    'url': '/login',
                    'data': {
                        'user': user,
                        'pwd': pwd
                    },
                    "success": function (data) {
                        if (data['code'] == 200) {
                            window.location = '/index'
                        } else {
                            var error = data['error'];
                            $("#error").html(error);
                            $("#error").show();
                        }
                    },
                    'fail': function (error) {
                        consle.log(error)
                    }
                });
            });
        });
    </script>
</head>

<body>

<div class="container">

    <form class="form-signin" method="post">
        <h3 class="form-signin-heading">{{ app_name }}</h3>
        <label for="inputName" class="sr-only">用户名</label>
        <input type="text" id="inputName" class="form-control" placeholder="用户名" name="user" required autofocus>
        <label for="inputPassword" class="sr-only">密码</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="密码" name="pwd" required>

        <button class="btn btn-lg btn-primary btn-block" id="submit" type="submit">Login</button>

        <p class="text-danger" style="display:none" id="error"></p>
    </form>

</div>
</body>
</html>

app/web_root/templates/error_404.html
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8">
    <title>
      该页面不存在
    </title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='img/favicon.png') }}">
    <style>
        * {
            margin:0;
            padding:0
        }

        @media screen and (min-width:768px) {
            #wrap {
                width:1180px;
                height:407px;
                position:absolute;
                top:50%;
                left:50%;
                margin-top:-224px;
                margin-left:-590px;
                display:flex;
                align-items:center
            }
            #wrap .text {
                float:right;
                position:relative;
                left:-125px;
                top:10px
            }
        }

        @media screen and (min-width:320px) and (max-width:767px) {
            html,body {
                height:100%
            }
            body {
                display:flex;
                align-items:center
            }
            #wrap,#wrap img {
                width:100%;
                margin-bottom:60px
            }
            #wrap .text {
                text-align:center
            }
        }
    </style>
  </head>
  
  <body>
    <div id="wrap">
      <div style="float: left">
        <img src="{{ url_for('static',filename='img/404.png') }}" alt="404.life" width="910" />
      </div>
      <div class="text">
        <p style="color: #0086F0;font-size: 26px;margin-bottom: 6px;">
          很抱歉
        </p>
        <p style="color: #0086F0;font-size: 22px;margin-bottom: 20px;">
          您访问的页面失联了
        </p>
        <a href="/index" style="color: #058b03;font-size: 22px;text-decoration: none;">
          点击这里 返回首页
        </a>
      </div>
    </div>
  </body>

</html>

app/web_root/templates/error_500.html
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8">
    <title>
      服务器异常
    </title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='img/favicon.png') }}">
    <style>
        * {
            margin:0;
            padding:0
        }

        @media screen and (min-width:768px) {
            #wrap {
                width:1180px;
                height:407px;
                position:absolute;
                top:50%;
                left:50%;
                margin-top:-224px;
                margin-left:-590px;
                display:flex;
                align-items:center
            }
            #wrap .text {
                float:right;
                position:relative;
                left:-125px;
                top:10px
            }
        }

        @media screen and (min-width:320px) and (max-width:767px) {
            html,body {
                height:100%
            }
            body {
                display:flex;
                align-items:center
            }
            #wrap,#wrap img {
                width:100%;
                margin-bottom:60px
            }
            #wrap .text {
                text-align:center
            }
        }
    </style>
  </head>
  
  <body>
    <div id="wrap">
      <div style="float: left">
        <img src="{{ url_for('static',filename='img/500.png') }}" alt="500.life" width="910" />
      </div>
      <div class="text">
        <p style="color: #bf0228;font-size: 26px;margin-bottom: 6px;">
          很抱歉
        </p>
        <p style="color: #bf0228;font-size: 22px;margin-bottom: 20px;">
          服务器突然崩溃了
        </p>
        <a href="/index" style="color: #058b03;font-size: 22px;text-decoration: none;">
          点击这里 返回首页
        </a>
      </div>
    </div>
  </body>

</html>

app/web_root/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ app_name }}</title>
    <link rel="icon" href="{{ url_for('static',filename='img/favicon.png') }}">
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/index.css') }}" rel="stylesheet">
    <script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>

</head>
<body>
<div class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <div class="navbar-brand">
                {{ app_name }}
            </div>
        </div>
        <ul class="nav navbar-nav" style="margin-top: 8px">
            <li><button type="button" class="btn btn-primary" onclick="window.location.href='{{ url_for('home.index') }}';">首页</button></li>
        </ul>

        <ul class="nav navbar-nav navbar-right" style="margin-top: 8px">
            <li><button type="button" class="btn btn-success" data-toggle="modal" data-target="#newDirectory">新建目录</button></li>
            <li><button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">上传文件</button></li>
            <li><button type="button" class="btn btn-danger" onclick="window.location.href='{{ url_for('account.logout') }}';">退出</button></li>
        </ul>
    </div>
</div>

<div class="modal fade" id="newDirectory" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">
                    请输入目录名称
                </h4>
            </div>
            <div class="modal-body">
                <input type="text" class="form-control" id="newDirName" aria-describedby="basic-addon3">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button id='createDirOk' class="btn btn-primary " data-dismiss="modal">确定</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">
                    请选择所需上传的本地文件
                </h4>
            </div>
            <div class="modal-body">
                <form id="upload-form" enctype="multipart/form-data">
                    <input id='file' class="btn btn-info" name="upload_file" type="file" accept=".mp3,.wav">
                </form>
                <!-- 上传进度： -->
                <progress></progress>
                <!-- <br/>
                <p id="progress">0 bytes</p>
                <p id="info"></p> -->
            </div>
            <div class="modal-footer">
                <button id='upload' class="btn btn-primary ">上传</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            </div>
        </div>
    </div>
</div>

<div class="container">
    {% if error_info %}
    <p class="text-danger" id="error">{{ error_info }}</p>
    {% endif %}
    {% if not path %}
    <h4>当前路径：/ </h4>
    {% else %}
    <h4>当前路径：
        {% for p in path|split_path %}
        <span>/</span>
        <a href="{{ url_for('home.index',path_uri=p[1]) }}">{{ p[0] }}</a>
        {% endfor %}
    </h4>
    {% endif %}
    <table class="table table-striped table-hover" id="myTable">
        <thead>
        <td>#</td>
        <td>名称</td>
        <td>修改时间</td>
        <td>类型</td>
        <td>大小</td>
        <td>操作</td>
        </thead>
        <tbody>
        {% for dir in dirs %}
        <tr>
            <td> {{ loop.index }}</td>
            {% if not path %}
            {% set link_uri = dir[0]|string %}
            {% else %}
            {% set link_uri = path + '/' + dir[0]|string %}
            {% endif %}
            <td><a href="{{ url_for('home.index',path_uri=link_uri) }}">{{ dir[0] }}</a></td>
            <td>{{ dir[1] }}</td>
            <td>{{ dir[2] }}</td>
            <td>{{ dir[3] }}</td>
            <td>
                <div class="btn btn-primary btn-sm " data-toggle="modal" data-target=".delConfirm" onclick="deleteResource(this)">删除</div>
            </td>
        </tr>
        {% endfor %}
        {% for file in files %}
        <tr>
            <td> {{ loop.index }}</td>
            {% if not path %}
            <td><a href="{{ url_for('home.download',filename=file[0]) }}">{{ file[0] }}</a></td>
            {% else %}
            <td><a href="{{ url_for('home.download',path=path,filename=file[0]) }}">{{ file[0] }}</a></td>
            {% endif %}
            <td>{{ file[1] }}</td>
            <td>{{ file[2] }}</td>
            <td>{{ file[3] }}</td>
            <td>
                <div class="btn btn-primary btn-sm " data-toggle="modal" data-target=".delConfirm" onclick="deleteResource(this)">删除</div>
            </td>
        </tr>
        {% endfor %}

        </tbody>
    </table>
</div>

<!-- 模态框   信息删除确认 -->
<div class="modal fade delConfirm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog">
        <div class="modal-content message_align">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                    aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">提示</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="deleteHideId" value=""/>
                <p id="deleteTitle">您确认要删除该资源吗？</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                    data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary"
                    id="confirmDelete">确认</button>
            </div>
        </div>
    </div>
</div>
<script>
    $('#upload').click(function () {
        var upload_path = {{path|tojson|safe}};

        var files = $('#file')[0].files;
        if(files.length == 0){
            return;
        }
        var filename = files[0].name;
        var file = files[0];
        var reader = new FileReader();
        audioContext = new (window.AudioContext || window.webkitAudioContext)();
        // When the file has been succesfully read
        reader.onload = function (event) {
            // Create an instance of AudioContext
            // Asynchronously decode audio file data contained in an ArrayBuffer.
            audioContext.decodeAudioData(event.target.result, function(buffer) {
                // Obtain the duration in seconds of the audio file (with milliseconds as well, a float value)
            });
        }
        reader.readAsArrayBuffer(file);
        if(file.name.endsWith('.mp3')) {
            if(audioContext.sampleRate != 48000) {
                alert("mp3采样率必须为48000");
                return;
            }
            if(audioContext.destination.channelCount != 2){
                alert("mp3采样率必须为双声道");
                return;
            }
        } else if (file.name.endsWith('.wav')) {
            if(audioContext.sampleRate != 24000) {
                alert("wav采样率必须为24000");
                return;
            }
            if(audioContext.destination.channelCount != 1){
                alert("mp3采样率必须为单声道");
                return;
            }
        }
        var formData = new FormData($('#upload-form')[0]);
        formData.append("upload_path", upload_path);
        $.post({
            url: '/upload',
            dataType: 'json',
            type: 'POST',
            data: formData,
            async: true,
            cashe: false,
            contentType: false,
            processData: false,
            success: function (returndata) {
                if(returndata['code'] == 200){
                    var info = returndata['info']
                    alert(info);
                    location.reload();
                }
            },
            error: function (returndata) {
                alert("上传失败！")
            },
            xhr: function () { 
                var _xhr = $.ajaxSettings.xhr();
                if (_xhr.upload) {
                    _xhr.upload.addEventListener('progress', progressHandling, false);
                }
                return _xhr;
            }
        })
    });

    function progressHandling(e) {
        if (e.lengthComputable) {
            $('progress').attr({value: e.loaded, max: e.total});
            var percent = e.loaded / e.total * 100;
            $('#progress').html(e.loaded + "/" + e.total + " bytes. " + percent.toFixed(2) + "%");
        }
    }

    $('#createDirOk').click(function () {
        var curPath = {{path|tojson|safe}};
        var dirName = $('#newDirName').val();
        var url = '/createdir/'
        if(curPath.length == 0) {
            url += dirName;
        }else {
            url += (curPath + '/' + dirName);
        }
        $.post({
            url: '/createdir/'+ curPath + '/' + dirName,
            dataType: 'json',
            type: 'POST',
            success: function (returndata) {
                if(returndata['code'] == 200){
                    location.reload();
                }else if(returndata['code'] != 304){
                    var info = returndata['info']
                    alert(info);
                }
            },
        });
    });
            
    function deleteResource(obj) {
        //attr() 方法设置或返回被选元素tr的属性值
        var $tds = $(obj).parent().parent().children();// 获取到所有列
        if($tds.length > 5) {
            var text = $tds[1].textContent;
            var type = $tds[3].textContent;
            $('#deleteHideId').val(text);
            var title = "";
            if(type === "文件夹"){
                title = "您确认要删除目录\"" + text + "\"吗？";
            }else{
                title = "您确认要删除文件\"" + text + "\"吗？";
            }
            $('#deleteTitle')[0].textContent = title;
        }
        // /$("#delConfirm").modal('show');
       }

    $("#confirmDelete").click(function() {
        var curPath = {{path|tojson|safe}};
        var name = $('#deleteHideId').val();
        var url = '/deleteResource/';
        if(curPath.length == 0) {
            url += name;
        }else {
            url += (curPath + "/" +  name);
        }
        $.post({
            url: url,
            dataType: 'json',
            type: 'POST',
            success: function (returndata) {
                if(returndata['code'] == 200){
                    location.reload();
                }else if(returndata['code'] != 304){
                    var info = returndata['info']
                    alert(info);
                }
            },
        });

    });
</script>
</body>
</html>